# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 485)
        self.lblImg = QtWidgets.QLabel(Dialog)
        self.lblImg.setGeometry(QtCore.QRect(40, 30, 281, 321))
        self.lblImg.setText("")
        self.lblImg.setObjectName("lblImg")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 360, 111, 41))
        self.label.setObjectName("label")
        self.lblResult = QtWidgets.QLabel(Dialog)
        self.lblResult.setGeometry(QtCore.QRect(320, 360, 151, 41))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.btnCut = QtWidgets.QPushButton(Dialog)
        self.btnCut.setGeometry(QtCore.QRect(200, 430, 91, 41))
        self.btnCut.setObjectName("btnCut")
        self.lblImg_cut = QtWidgets.QLabel(Dialog)
        self.lblImg_cut.setGeometry(QtCore.QRect(350, 40, 291, 311))
        self.lblImg_cut.setText("")
        self.lblImg_cut.setObjectName("lblImg_cut")
        self.btnUpload = QtWidgets.QPushButton(Dialog)
        self.btnUpload.setGeometry(QtCore.QRect(430, 430, 81, 41))
        self.btnUpload.setObjectName("btnUpload")

        self.retranslateUi(Dialog)
        self.btnCut.clicked.connect(Dialog.cutImage)
        self.btnUpload.clicked.connect(Dialog.loadImage)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "识别结果："))
        self.btnCut.setText(_translate("Dialog", "视频截取"))
        self.btnUpload.setText(_translate("Dialog", "本地上传"))
